### ISSUE TITLE
Harvey is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.danrabbit.harvey#1]
The Harvey page is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by jgarciao** [comment]
There was an issue with the app synching process. Is published now

https://flathub.org/apps/details/com.github.danrabbit.harvey
